//AUTH && Playing
export const SETUSER = "SETUSER";
export const SETTOKEN = "SETTOKEN";
export const RESETUSETANDTOKEN = "RESETUSETANDTOKEN";
export const SETPLAYLIST = "SETPLAYLIST";
export const SETDISCOVERWEEKLY = "SETDISCOVERWEEKLY";
export const SETSPOTIFYWEBAPI = "SETSPOTIFYWEBAPI";
export const TOGGLEPLAYING = "TOGGLEPLAYING";
export const SETITEM = "SETITEM"; 